// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://easwhndrknudvdubiaju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhc3dobmRya251ZHZkdWJpYWp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTQyNzEsImV4cCI6MjA1OTk5MDI3MX0._MuxxQ3kktOQTGIrMSiVpPrcYDMDFIdVKNRFlLkgewM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);